# Generated by Django 5.0.4 on 2026-08-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tag_type', models.CharField(choices=[('exam', 'Exam'), ('section', 'Section'), ('topic', 'Topic'), ('difficulty', 'Difficulty'), ('source', 'Source'), ('type', 'Question Type')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tools.tag')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('word_count', models.IntegerField(null=True)),
                ('difficulty', models.IntegerField(default=3)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='passages', to='tools.tag')),
            ],
            options={
                'db_table': 'passages',
                'ordering': ['tool', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tool_type', models.CharField(choices=[('rc_passages', 'RC Passages'), ('qa_topics', 'QA Topics'), ('vocabulary', 'Vocabulary'), ('mcq_practice', 'MCQ Practice'), ('grammar', 'Grammar'), ('gk', 'General Knowledge'), ('reasoning', 'Reasoning'), ('legal', 'Legal Awareness')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_lead_gate', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=0)),
                ('og_image_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_desc', models.CharField(blank=True, max_length=320)),
                ('access_model', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('price_inr', models.DecimalField(blank=True, decimal_places=2, help_text='Price if access_model is premium', max_digits=8, null=True)),
                ('razorpay_plan_id', models.CharField(blank=True, help_text='Razorpay subscription plan ID for premium tools', max_length=80)),
                ('preview_questions', models.IntegerField(default=5, help_text='How many questions are shown free before the paywall')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. "New" or "Premium" — shown on tool card', max_length=40)),
                ('tags', models.ManyToManyField(blank=True, related_name='tools', to='tools.tag')),
            ],
            options={
                'db_table': 'tools',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_position', models.IntegerField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ — Single Correct'), ('mcq_multi', 'MCQ — Multiple Correct'), ('tita', 'TITA — Numeric'), ('vocab', 'Vocabulary'), ('grammar', 'Grammar'), ('gk', 'General Knowledge')], default='mcq', max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('correct_answer', models.CharField(blank=True, max_length=20)),
                ('marks_correct', models.DecimalField(decimal_places=2, default=3, max_digits=4)),
                ('marks_wrong', models.DecimalField(decimal_places=2, default=-1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_tag', models.CharField(blank=True, db_index=True, max_length=30)),
                ('section_tag', models.CharField(blank=True, db_index=True, max_length=30)),
                ('topic_tag', models.CharField(blank=True, db_index=True, max_length=100)),
                ('difficulty_tag', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source_tag', models.CharField(blank=True, db_index=True, max_length=80)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tools.passage')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='tools.tag')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tools.tool')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QATopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('arithmetic', 'Arithmetic'), ('algebra', 'Algebra'), ('geometry', 'Geometry & Mensuration'), ('number', 'Number Theory'), ('modern', 'Modern Math'), ('logic', 'Logical Reasoning')], max_length=20)),
                ('concept_notes', models.TextField(blank=True)),
                ('formulas', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(blank=True, help_text='Topic tag — links questions to this topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_topics', to='tools.tag')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_topics', to='tools.tool')),
            ],
            options={
                'db_table': 'qa_topics',
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='tools.tool'),
        ),
        migrations.CreateModel(
            name='ToolLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('target_exam', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(blank=True, max_length=256)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tools.tool')),
            ],
            options={
                'db_table': 'tool_leads',
            },
        ),
        migrations.CreateModel(
            name='ToolSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('questions_seen', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('score_pct', models.FloatField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tools.toollead')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
            options={
                'db_table': 'tool_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(blank=True, max_length=20)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_spent_secs', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tools.toolsession')),
            ],
            options={
                'db_table': 'tool_answers',
            },
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('etymology', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('synonyms', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('high', 'High Frequency'), ('medium', 'Medium Frequency'), ('low', 'Low Frequency')], default='medium', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab_word', to='tools.question')),
                ('tags', models.ManyToManyField(blank=True, to='tools.tag')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_words', to='tools.tool')),
            ],
            options={
                'db_table': 'vocab_words',
                'ordering': ['sort_order', 'word'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tools.question')),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['key'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='tags_tag_typ_766b27_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_tag', 'section_tag'], name='questions_exam_ta_43ed7e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['tool', 'is_active'], name='questions_tool_id_c90ade_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_tag'], name='questions_difficu_3cfda7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qatopic',
            unique_together={('tool', 'number')},
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['tool', 'difficulty'], name='passages_tool_id_22a2c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='passage',
            unique_together={('tool', 'number')},
        ),
        migrations.AddIndex(
            model_name='toollead',
            index=models.Index(fields=['email', 'tool'], name='tool_leads_email_dc63c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toollead',
            unique_together={('email', 'tool')},
        ),
        migrations.AddIndex(
            model_name='vocabword',
            index=models.Index(fields=['difficulty'], name='vocab_words_difficu_349914_idx'),
        ),
    ]
