# Generated by Django 5.0.4 on 2026-08-06 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('in_app', 'In-App'), ('both', 'Both')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('title_template', models.CharField(blank=True, max_length=200)),
                ('body_template', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('enrollment', 'Enrollment'), ('payment', 'Payment'), ('session', 'Live Session'), ('mock', 'Mock Test'), ('content', 'New Content'), ('system', 'System'), ('achievement', 'Achievement')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'in_app_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='in_app_noti_user_id_75f459_idx'), models.Index(fields=['user', '-created_at'], name='in_app_noti_user_id_82d160_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('template', models.CharField(choices=[('enrollment_confirmed', 'Enrollment Confirmed'), ('session_reminder', 'Session Reminder'), ('payment_failed', 'Payment Failed'), ('mock_available', 'New Mock Available'), ('welcome', 'Welcome Message'), ('custom', 'Custom Message')], max_length=40)),
                ('body_preview', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_msg_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='whatsapp_lo_phone_ec768f_idx'), models.Index(fields=['status'], name='whatsapp_lo_status_d95a49_idx'), models.Index(fields=['template', 'status'], name='whatsapp_lo_templat_25e496_idx')],
            },
        ),
    ]
