# Generated by Django 5.0.4 on 2026-08-06 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='courses.exam')),
            ],
            options={
                'db_table': 'pdfs',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pdfs.pdf')),
            ],
            options={
                'db_table': 'pdf_pages',
                'ordering': ['page_number'],
                'unique_together': {('pdf', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='PdfPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=256)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('phone_captured', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='pdfs.pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'pdf'], name='pdf_purchas_user_id_1a9910_idx'), models.Index(fields=['razorpay_order_id'], name='pdf_purchas_razorpa_6e0ea3_idx')],
            },
        ),
    ]
