# Generated by Django 5.0.4 on 2026-08-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='foundation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='foundations.foundationclass'),
        ),
    ]
