# Generated by Django 5.0.4 on 2026-08-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyq', '0001_initial'),
        ('pdfs', '0002_pdf_foundation_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='fyq_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='fyq.fyqquestion'),
        ),
    ]
