# Generated by Django 5.0.4 on 2026-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0003_pdf_fyq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='card_label',
            field=models.CharField(blank=True, help_text='Overrides the default "PDF" badge shown on the card (e.g. class detail sidebar). Leave blank to show "PDF".', max_length=30),
        ),
    ]