# Generated by Django 5.0.4 on 2026-08-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams', models.JSONField(default=list, help_text='List of exam codes this series applies to, e.g. ["xat","snap"]. Set via the admin checkboxes, not typed directly.')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content_types', models.JSONField(default=list, help_text='Which of these applies — pick one or both. Purely for your own reference; the actual public page framing per exam is fixed by URL, not by this field.')),
                ('notes', models.TextField(blank=True, help_text='Rich HTML content covering the whole series — formulas, images, links. Added via admin editor. Shown on the public listing page above the class list.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Foundation Series',
                'db_table': 'foundation_series',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoundationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(help_text='e.g. 1, 2, 3 — order within the series')),
                ('title', models.CharField(help_text='e.g. "Decision Making — Analytical Reasoning"', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, help_text='What this class covers — shown on the listing page')),
                ('scheduled_at', models.DateTimeField(help_text='Date and time of the live class (IST)')),
                ('duration_mins', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('youtube_url', models.URLField(blank=True, help_text='Paste YouTube URL after the class is recorded — activates the recording on the page')),
                ('notes', models.TextField(blank=True, help_text='Rich HTML content — notes, images, formulas for this class. Added via admin editor.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='foundations.foundationseries')),
            ],
            options={
                'db_table': 'foundation_classes',
                'ordering': ['series', 'lesson_number'],
                'unique_together': {('series', 'lesson_number')},
            },
        ),
    ]
