# Generated by Django 5.0.4 on 2026-08-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundationclass',
            name='long_description',
            field=models.TextField(blank=True, help_text='A few real paragraphs about what this video covers — this is the main text search engines and AI answer engines will read and cite. Shown prominently on the class page, above the video.'),
        ),
    ]
