# Generated by Django 5.0.4 on 2026-08-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0002_foundationclass_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundationclass',
            name='exams',
            field=models.JSONField(blank=True, default=list, help_text="Leave empty to inherit every exam the series is tagged with. Set specific exams here only if this particular video isn't relevant to all of them."),
        ),
    ]
