# Generated by Django 5.0.4 on 2026-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0003_foundationclass_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundationclass',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description shown in Google search results. Falls back to the short description above if left blank. Keep it under ~155 characters for best display.', max_length=300),
        ),
    ]
