# Generated by Django 5.0.4 on 2026-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0006_instructor_name_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
