# Generated by Django 5.0.4 on 2026-08-06 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search: e.g. "varc,rc,strategy"', max_length=300)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_source', models.CharField(choices=[('bunny', 'Bunny Stream'), ('youtube', 'YouTube')], default='bunny', max_length=10)),
                ('bunny_video_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bunny_library_id', models.CharField(blank=True, max_length=20)),
                ('youtube_video_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('duration_secs', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_exam', models.ForeignKey(blank=True, help_text='Exam this video was originally created for. Used for filtering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_videos', to='courses.exam')),
            ],
            options={
                'db_table': 'video_library',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_transcript', models.TextField(blank=True)),
                ('ai_notes', models.TextField(blank=True)),
                ('word_count', models.IntegerField(null=True)),
                ('processing_secs', models.FloatField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='content.videolibrary')),
            ],
            options={
                'db_table': 'ai_transcripts',
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_secs', models.IntegerField(default=0)),
                ('last_position', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.videolibrary')),
            ],
            options={
                'db_table': 'video_progress',
            },
        ),
        migrations.AddIndex(
            model_name='videolibrary',
            index=models.Index(fields=['primary_exam', 'is_published'], name='video_libra_primary_b38d58_idx'),
        ),
        migrations.AddIndex(
            model_name='videolibrary',
            index=models.Index(fields=['bunny_video_id'], name='video_libra_bunny_v_25ca5d_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'video'], name='video_progr_user_id_a03f41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('user', 'video')},
        ),
    ]
