# Generated by Django 5.0.4 on 2026-08-31 18:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[("mock", "Full Mock"), ("sectional", "Sectional")],
                        max_length=12,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'SNAP Mock 1' or 'SNAP Sectional — Quant-DI-DS Set 3'",
                        max_length=200,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "is_free",
                    models.BooleanField(
                        default=False,
                        help_text="Bypasses the paid-access AND the unlock-progression gate — always attemptable.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "release_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank = available immediately once active.",
                        null=True,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_papers",
                        to="courses.exam",
                    ),
                ),
            ],
            options={
                "db_table": "mock_papers",
                "ordering": ["exam", "test_type", "sort_order", "-created_at"],
                "unique_together": {("exam", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MockSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'General English', 'Quant-DI-DS' — free text, not a fixed exam-wide list",
                        max_length=60,
                    ),
                ),
                ("time_limit_mins", models.IntegerField(default=40)),
                ("order", models.IntegerField(default=1)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="mocks.mockpaper",
                    ),
                ),
            ],
            options={
                "db_table": "mock_sections",
                "ordering": ["order"],
                "unique_together": {("paper", "name")},
            },
        ),
        migrations.CreateModel(
            name="MockPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passage_text",
                    models.TextField(
                        help_text="RC passage or DILR set prompt. HTML allowed."
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="mocks.mocksection",
                    ),
                ),
            ],
            options={
                "db_table": "mock_passages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MockTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text="Must match the MockSection.name this topic applies to, e.g. 'QA-DI-DS'",
                        max_length=60,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180)),
                ("order", models.IntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_topics",
                        to="courses.exam",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="mocks.mocktopic",
                    ),
                ),
            ],
            options={
                "db_table": "mock_topics",
                "ordering": ["section_name", "order", "name"],
                "unique_together": {("exam", "section_name", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MockQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("TITA", "Type In The Answer"),
                        ],
                        default="MCQ",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.TextField(blank=True)),
                ("option_b", models.TextField(blank=True)),
                ("option_c", models.TextField(blank=True)),
                ("option_d", models.TextField(blank=True)),
                (
                    "option_e",
                    models.TextField(
                        blank=True,
                        help_text="Optional 5th option (XAT-style). Leave blank for 4-option questions.",
                    ),
                ),
                (
                    "correct_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                ("tita_answer", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "correct_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3"), max_digits=4
                    ),
                ),
                (
                    "negative_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Deducted on a wrong MCQ answer. TITA wrong answers score 0 by convention — leave negative_marks unused for TITA.",
                        max_digits=4,
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "passage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="mocks.mockpassage",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mocks.mocksection",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Drives topic-wise practice — a topic-wise attempt pulls questions by this tag, regardless of which paper authored them.",
                        related_name="questions",
                        to="mocks.mocktopic",
                    ),
                ),
            ],
            options={
                "db_table": "mock_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MockAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("full", "Full Mock"),
                            ("sectional", "Sectional"),
                            ("topic", "Topic-wise"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_filter",
                    models.CharField(
                        blank=True,
                        help_text="easy/moderate/hard/'' for topic-wise",
                        max_length=10,
                    ),
                ),
                ("question_count_requested", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="started_at + duration; used for resume + auto-submit"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_auto_submitted", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("correct", models.IntegerField(default=0)),
                ("incorrect", models.IntegerField(default=0)),
                ("unattempted", models.IntegerField(default=0)),
                ("section_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_attempts",
                        to="courses.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for full/sectional",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mocks.mockpaper",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for sectional (== paper.sections.first())",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mocks.mocksection",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for topic-wise",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="mocks.mocktopic",
                    ),
                ),
            ],
            options={
                "db_table": "mock_attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MockResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A-E for MCQ, typed answer for TITA",
                    ),
                ),
                ("is_visited", models.BooleanField(default=False)),
                ("is_marked_for_review", models.BooleanField(default=False)),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "marks_awarded",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=4
                    ),
                ),
                ("time_taken_secs", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="mocks.mockattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="mocks.mockquestion",
                    ),
                ),
            ],
            options={
                "db_table": "mock_responses",
                "unique_together": {("attempt", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="mockquestion",
            index=models.Index(
                fields=["section", "difficulty"], name="mock_questi_section_df881b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mockquestion",
            index=models.Index(
                fields=["section", "question_type"],
                name="mock_questi_section_e6f48b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mockquestion",
            index=models.Index(
                fields=["passage"], name="mock_questi_passage_d92d36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mockattempt",
            index=models.Index(
                fields=["user", "exam", "completed"],
                name="mock_attemp_user_id_9dbbcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mockattempt",
            index=models.Index(
                fields=["user", "paper", "completed"],
                name="mock_attemp_user_id_a81399_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mockattempt",
            index=models.Index(
                fields=["user", "topic", "completed"],
                name="mock_attemp_user_id_555f96_idx",
            ),
        ),
    ]
