# Generated by Django 5.0.4 on 2026-08-31 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mockquestion",
            name="topics",
        ),
        migrations.AddField(
            model_name="mockquestion",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only for topic-wise practice questions — its own separate pool, not shared with mocks/sectionals.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="mocks.mocktopic",
            ),
        ),
        migrations.AlterField(
            model_name="mockquestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="mocks.mocksection",
            ),
        ),
        migrations.AlterField(
            model_name="mocktopic",
            name="section_name",
            field=models.CharField(
                help_text="Which real exam section this topic belongs to, e.g. 'QA-DI-DS' — grouping only, doesn't link to a MockSection's own question pool.",
                max_length=60,
            ),
        ),
        migrations.AddIndex(
            model_name="mockquestion",
            index=models.Index(
                fields=["topic", "difficulty"], name="mock_questi_topic_i_7673a8_idx"
            ),
        ),
    ]
