# Generated by Django 5.0.4 on 2026-08-06 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_attend_live', models.BooleanField(default=False)),
                ('can_watch_recordings', models.BooleanField(default=False)),
                ('can_take_mocks', models.BooleanField(default=False)),
                ('can_download_books', models.BooleanField(default=False)),
                ('can_access_gdpi', models.BooleanField(default=False)),
                ('mock_exams_unlocked', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='courses.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_accesses',
                'indexes': [models.Index(fields=['user', 'exam'], name='course_acce_user_id_4a54e7_idx')],
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='payments.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.pricingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['user', 'status'], name='enrollments_user_id_b5f69f_idx'), models.Index(fields=['plan', 'status'], name='enrollments_plan_id_cfe905_idx')],
            },
        ),
    ]
