# Generated by Django 5.0.4 on 2026-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FYQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='e.g. 70 — the FYQ number, shown as "Future Year Question 070"', unique=True)),
                ('exams', models.JSONField(default=list, help_text='Which exams this question is relevant to — check every exam it applies to.')),
                ('title', models.CharField(help_text='e.g. "Averages & Mixtures — Future Year Question 070"', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('topic', models.CharField(blank=True, help_text='e.g. "Averages & Mixtures" — used for filtering on the public page', max_length=100)),
                ('youtube_url', models.URLField(blank=True, help_text='Solution walkthrough video')),
                ('long_description', models.TextField(blank=True, help_text='The question and full explanation, written up like a blog post — real content for search engines and AI answer engines to read and cite.')),
                ('notes', models.TextField(blank=True, help_text='Additional rich HTML notes/resources, optional')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FYQ Question',
                'verbose_name_plural': 'FYQ Questions',
                'db_table': 'fyq_questions',
                'ordering': ['-question_number'],
            },
        ),
    ]
