# Generated by Django 5.0.4 on 2026-08-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FYQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('has_categories', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'FYQ Sections',
                'db_table': 'fyq_sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='fyqquestion',
            name='exams',
        ),
        migrations.CreateModel(
            name='FYQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='fyq.fyqsection')),
            ],
            options={
                'verbose_name_plural': 'FYQ Categories',
                'db_table': 'fyq_categories',
                'ordering': ['order', 'name'],
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FYQTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='fyq.fyqcategory')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='fyq.fyqsection')),
            ],
            options={
                'verbose_name_plural': 'FYQ Topics',
                'db_table': 'fyq_topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='fyqquestion',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Where this question lives in the Section → Category → Topic browse tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='fyq.fyqtopic'),
        ),
    ]
