# Generated by Django 5.0.4 on 2026-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyq', '0002_fyqsection_remove_fyqquestion_exams_fyqcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fyqquestion',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description shown in Google search results. Falls back to a snippet of the long description if left blank. Keep it under ~155 characters for best display.', max_length=300),
        ),
    ]
