# Generated by Django 5.0.4 on 2026-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyq', '0004_fyqquestion_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyqquestion',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='Who solved this question. Leave blank to show "ALP Sir" (the default).', max_length=100),
        ),
    ]
