# Generated by Django 5.0.4 on 2026-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='body',
            field=models.TextField(blank=True, help_text='Full write-up / interview content for the detail page.'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='outcome_description',
            field=models.TextField(blank=True, help_text='One or two sentences of context shown inside the outcome box'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='outcome_label',
            field=models.CharField(blank=True, default='Outcome', help_text='Small label above the outcome box, e.g. "Outcome"', max_length=40),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='outcome_value',
            field=models.CharField(blank=True, help_text='The headline result shown in the outcome box, e.g. "NMIMS Mumbai — Core MBA"', max_length=150),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='pull_quote',
            field=models.CharField(blank=True, help_text='A short standout quote, styled larger and italic on the detail page', max_length=400),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from name. Used for the public /results/<slug> page.', max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subtitle',
            field=models.CharField(blank=True, help_text='One-line summary shown under the headline', max_length=300),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='tag',
            field=models.CharField(blank=True, help_text='Short badge shown above the headline, e.g. "NMIMS Convert", "Multiple Converts"', max_length=60),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='video_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('youtube', 'YouTube'), ('bunny', 'Bunny')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube: any normal watch/share link. Bunny: the direct iframe embed URL.'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='whatsapp_message',
            field=models.TextField(blank=True, help_text="The student's original message, rendered as a WhatsApp-style chat bubble. One line per paragraph."),
        ),
    ]