# Generated by Django 5.0.4 on 2026-08-06 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DripSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(blank=True, choices=[('tool_gate', 'Tool Gate Submit'), ('registration', 'Account Registration'), ('checkout_abandon', 'Checkout Abandoned'), ('manual', 'Manual Enrollment'), ('post_purchase', 'Post Purchase')], max_length=30)),
                ('trigger_exam', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drip_sequences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DripEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(blank=True, max_length=160)),
                ('html_body', models.TextField(help_text='Use {{ first_name }}, {{ exam }}, {{ unsubscribe_url }} as template vars.')),
                ('send_delay_hours', models.IntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='leads.dripsequence')),
            ],
            options={
                'db_table': 'drip_emails',
                'ordering': ['sequence', 'step'],
                'unique_together': {('sequence', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('target_exam', models.CharField(blank=True, choices=[('CAT', 'CAT'), ('GMAT', 'GMAT'), ('GRE', 'GRE'), ('IPMAT', 'IPMAT'), ('XAT', 'XAT'), ('SNAP', 'SNAP'), ('NMAT', 'NMAT'), ('CMAT', 'CMAT'), ('MHCET', 'MH CET'), ('CLAT', 'CLAT'), ('CUET', 'CUET'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('engaged', 'Engaged'), ('nurtured', 'Nurtured'), ('converted', 'Converted'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='new', max_length=20)),
                ('lead_score', models.IntegerField(default=0)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('referrer_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('converted_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='courses.pricingplan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resend_email_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Spam Complaint'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('link_clicked', models.URLField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('drip_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.dripemail')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='leads.lead')),
            ],
            options={
                'db_table': 'email_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DripEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leads.dripsequence')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_enrollments', to='leads.lead')),
            ],
            options={
                'db_table': 'drip_enrollments',
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('tool_gate', 'Tool Gate'), ('blog_subscribe', 'Blog Subscribe'), ('course_page', 'Course Page CTA'), ('checkout', 'Checkout (Abandoned)'), ('registration', 'Account Registration'), ('manual', 'Manual Import'), ('referral', 'Referral'), ('organic', 'Organic Search'), ('paid', 'Paid Ad'), ('social', 'Social Media'), ('whatsapp', 'WhatsApp')], max_length=30)),
                ('source_detail', models.CharField(blank=True, max_length=255)),
                ('is_first_touch', models.BooleanField(default=False)),
                ('is_last_touch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_94f025_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['target_exam', 'status'], name='leads_target__79a9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_score'], name='leads_lead_sc_40809e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_created_e6e479_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['lead', 'event_type'], name='email_event_lead_id_28da9b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='email_event_event_t_b77aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='dripenrollment',
            index=models.Index(fields=['status', 'next_send_at'], name='drip_enroll_status_69e298_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dripenrollment',
            unique_together={('lead', 'sequence')},
        ),
    ]
